server:
  port: 8080

spring:
  application:
    name: spring-auth-api

springdoc:
  api-docs:
    path: /api/v1/openapi
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
